name: Release
on:
  release:
    types:
      - published

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: latest
          actions-cache-folder: ".emsdk-cache"

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: ".xmake-cache"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.x
          run_install: true

      - name: Build packages
        run: pnpm run build

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-result
          path: packages/*/dist/

  # --- Comming soon ---

  #  test:
  #    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
  #    needs: [build]
  #    runs-on: ${{ matrix.os }}
  #    strategy:
  #      matrix:
  #        node_version: ["18", "16"]
  #        os: [ubuntu-latest]
  #
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v3
  #
  #      - name: Download build result
  #        uses: actions/download-artifact@v3
  #        with:
  #          name: build-result
  #          path: packages/
  #
  #      - name: Setup Node.js ${{ matrix.node_version }}
  #        uses: actions/setup-node@v3
  #        with:
  #          node-version: ${{ matrix.node_version }}
  #
  #      - name: Setup pnpm
  #        uses: pnpm/action-setup@v2
  #        with:
  #          version: 7.x
  #          run_install: true
  #
  #      - name: Run tests
  #        run: pnpm test

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download build result
        uses: actions/download-artifact@v3
        with:
          name: build-result
          path: packages/

      - name: Setup Node.js 
        uses: actions/setup-node@v3 
        with: 
          node-version: 18
 
      - name: Setup pnpm 
        uses: pnpm/action-setup@v2 
        with: 
          version: 7.x 
          run_install: true 

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --no-git-checks
